### ISSUE TITLE
看不懂conan的操作步骤的留个爪。。是不是只有我没看懂

### ISSUE THREAD

**Issue by midGitub** [jinq0123/LuaPbIntf#12]

**Comment by jinq0123** [comment]
conan 只是简化库依赖。编译可直接看 src/CMakeLists.txt:
```
add_compile_options(-std=c++11) 
file(GLOB_RECURSE SRC_LIST "*.cpp") 
add_library(luapbintf ${SRC_LIST}) 
```

**Comment by yaoxin125** [comment]
希望可以支持cmake or make 编译 看了一下 感觉这个还是挺不错的，就是不喜欢dock或者conan 又需要安装一大堆 东西，

**Comment by jinq0123** [comment]
cmake, make 都是支持的。

cmake需要安装cmake，使用 src/CMakeLists.txt. 

生成 Makefile 需要安装 premake5, 并执行 `premake5 --os=linux gmake` 生成，见 premake/ 目录。
