### ISSUE TITLE
build succes,but use fail

### ISSUE THREAD

**Issue by dqzg12300** [jinq0123/LuaPbIntf#13]
luapbintf.so: undefined symbol: _Z14lua_pushstringP9lua_StatePKc

**Comment by dqzg12300** [comment]
luapbintf/third_party/lib
Are they placed in the directory
liblua.a
libprotobuf.a

**Comment by dqzg12300** [comment]
change libprotobuf.so build success
but
undefined symbol: _Z14lua_pushstringP9lua_StatePKc
The problem still exists

**Comment by jinq0123** [comment]
It expects the Lua library to build under C++.

**Comment by dqzg12300** [comment]
defines { "LUAINTF_LINK_LUA_COMPILED_IN_CXX=0" }
这个要加在哪里?

**Comment by dqzg12300** [comment]
ERROR: Error downloading file https://www.lua.org/ftp/lua-5.3.4.tar.gz: 'HTTPSConnectionPool(host='www.lua.org', port=443): Max retries exceeded with url: /ftp/lua-5.3.4.tar.gz (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:765)'),))'
Waiting 5 seconds to retry...
lua-cpp/5.3.4@jinq0123/testing: WARN: Trying to remove corrupted source folder
lua-cpp/5.3.4@jinq0123/testing: WARN: This can take a while for big packages
ERROR: lua-cpp/5.3.4@jinq0123/testing: Error in source() method, line 21
        tools.download(url, zip_name)
        ConanConnectionError: Download failed, check server, possibly try again
HTTPSConnectionPool(host='www.lua.org', port=443): Read timed out.

使用conan来编译是报这个错误

**Comment by dqzg12300** [comment]
defines { "LUAINTF_LINK_LUA_COMPILED_IN_CXX=0" }
这个把premake5.lua里面的这行解注释了重新编译也是同样的错误

**Comment by dqzg12300** [comment]
在LuaPbInft.make中有 DEFINES += -DLUAINTF_LINK_LUA_COMPILED_IN_CXX=0 -DNDEBUG

**Comment by dqzg12300** [comment]
我编译window的试了下。发现碰到和issues #2 的情况一模一样。
但是我看了premake5.lua里面有defines { "LUAINTF_LINK_LUA_COMPILED_IN_CXX=0" }
并且makefile里面也有DEFINES += -DLUAINTF_LINK_LUA_COMPILED_IN_CXX=0
依然还是无法解析的外部符号一堆

**Comment by jinq0123** [comment]
如果是这样，找不到 `_lua_pushvalue`：
```
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 _lua_pushvalue，该符号在函数 "public: __thiscall LuaIntf::LuaRef::LuaRef(struct lua_State *,int)" (??0LuaRef@LuaIntf@@QAE@PAUlua_State@@H@Z) 中被引用
```
说明试图链接 lua 的C库。
如果是`_Z14lua_pushstringP9lua_StatePKc`, 说明试图链接lua的C++库。
从符号名可以判断`LUAINTF_LINK_LUA_COMPILED_IN_CXX`是否生效。
贴一下出错信息吧，这样才能看到问题。

**Comment by dqzg12300** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 lua_type，该符号在函数 "public: static class LuaIntf::LuaRef __cdecl LuaIntf::LuaTypeMapping<class LuaIntf::LuaRef,void>::get(struct lua_State *,int)" (?get@?$LuaTypeMapping@VLuaRef@LuaIntf@@X@LuaIntf@@SA?AVLuaRef@2@PEAUlua_State@@H@Z) 中被引用	LuaPbIntf	F:\king\LuaPbIntf\premake\vs2015\LuaPbIntf.obj	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "void __cdecl lua_pushvalue(struct lua_State *,int)" (?lua_pushvalue@@YAXPEAUlua_State@@H@Z)，该符号在函数 "public: __cdecl LuaIntf::LuaRef::LuaRef(struct lua_State *,int)" (??0LuaRef@LuaIntf@@QEAA@PEAUlua_State@@H@Z) 中被引用	LuaPbIntf	F:\king\LuaPbIntf\premake\vs2015\MessageSetter.obj	1	

这种错误很多条。我看了下。你的config.h里面没有用extern "C"。不过我加上了也没用。

**Comment by dqzg12300** [comment]
_Z14lua_pushstringP9lua_StatePKc
这个错误是使用linux编译的错误。上面的是window编译的错误

**Comment by jinq0123** [comment]
我编译了lua C库，然后在 Config.h 中加了 extern C, 编译成功了。
lua.lib中有`_lua_type`:
```
λ  "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /EXPORTS lua53.lib | findstr lua_type
                  _lua_type
                  _lua_typename
```
但是不知道你为什么去链接 `lua_type`. 应该有下划线才对。

**Comment by dqzg12300** [comment]
我猜测可能和我用的lua版本有关系。你是使用什么版本的lua？我用的5.3.4

**Comment by jinq0123** [comment]
我也是。

**Comment by dqzg12300** [comment]
你的luaIntf的里面是不是还有个lua的src啥的？
我只把lua的src放到LuaPbIntf的third_party/lua

**Comment by dqzg12300** [comment]
给我的感觉是luaPbIntf能找到lua
但是LuaIntf没有找到lua

**Comment by jinq0123** [comment]
```
E:\Git\LuaPbIntf\third_party (master -> origin)       
λ tree                                                
卷 文档 的文件夹 PATH 列表                                     
卷序列号为 000F-54F9                                       
E:.                                                   
├─lib                                                 
│  ├─Debug                                            
│  └─Release                                          
├─lua                                                 
│  └─src                                              
├─lua-intf                                            
│  └─LuaIntf                                          
│      ├─impl                                         
│      └─src                                          
└─protobuf                                            
    ├─benchmarks                                      
    ├─cmake                                           
```

**Comment by dqzg12300** [comment]
看了。路径没啥问题。基本你的README需要的都放了。lua-intf是只要放在那个位置就行了么？没有什么其他相关的处理么？

**Comment by jinq0123** [comment]
更新下 Config.h, 然后再贴下vs2015的出错信息。

**Comment by dqzg12300** [comment]
更新后window也是一模一样的错误。没有任何改变
不过我重新编译linux的试了下。linux的正常了。

**Comment by jinq0123** [comment]
```C++
template <>
struct LuaTypeMapping <LuaRef>
{
    static LuaRef get(lua_State* L, int index)
    {
        return lua_isnone(L, index) ? LuaRef() : LuaRef(L, index);
    }
}
```
`LuaTypeMapping<class LuaIntf::LuaRef,void>::get()` 没有调用 `lua_type()` 啊？为什么会报这个错：
```
错误 LNK2019 无法解析的外部符号 lua_type，该符号在函数 "public: static class LuaIntf::LuaRef __cdecl LuaIntf::LuaTypeMapping<class LuaIntf::LuaRef,void>::get(struct lua_State *,int)" (?get@?$LuaTypeMapping@VLuaRef@LuaIntf@@x@LuaIntf@@sa?AVLuaRef@2@PEAUlua_State@@h@Z) 中被引用 LuaPbIntf F:\king\LuaPbIntf\premake\vs2015\LuaPbIntf.obj 1
```

**Comment by dqzg12300** [comment]
LUA_INLINE LuaTypeID LuaRef::type() const
{
    if (m_ref == LUA_NOREF) {
        return LuaTypeID::NONE;
    } else if (m_ref == LUA_REFNIL) {
        return LuaTypeID::NIL;
    } else {
        pushToStack();
        int t = lua_type(L, -1);
        lua_pop(L, 1);
        return static_cast<LuaTypeID>(t);
    }
}

在LuaRef和Lua_State中有lua_type的使用。虽然你发的函数没有使用。但是肯定有初始化这个类型之类的把。

**Comment by dqzg12300** [comment]
linux的能用也可以了。我先用着把。谢谢

**Comment by jinq0123** [comment]
lua.lib不对时，我也会报这个错：
```
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 _lua_type，该符号在函数 "public: static class LuaIntf::LuaRef __cdecl LuaIntf::LuaTypeMapping<class LuaIntf::LuaRef,void>::get(struct lua_State *,int)" (?get@?$LuaTypeMapping@VLuaRef@LuaIntf@@X@LuaIntf@@SA?AVLuaRef@2@PAUlua_State@@H@Z) 中被引用	LuaPbIntf	E:\Git\LuaPbIntf\premake\vs2015\LuaPbIntf.obj	1	
```

**Comment by dqzg12300** [comment]
lua.lib什么情况会不对？
