### ISSUE TITLE
声明的时候报错是什么情况？

### ISSUE THREAD

**Issue by dqzg12300** [jinq0123/LuaPbIntf#14]
package.cpath = "../luaclib/?.so;"
local pb=require("luapbintf")
报下面的错误。是不是我还少包含了什么？
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)

**Comment by jinq0123** [comment]
没碰到过。需要找到哪里抛异常。

**Comment by jinq0123** [comment]
可能需要编译时加上  -lpthread
http://bbs.chinaunix.net/forum.php?mod=viewthread&tid=4252692&orderby=dateline&orderby=dateline

**Comment by jinq0123** [comment]
Modify premake/premake5.lua:
```
    filter { "system:linux" }
-        links { "protobuf" }
+       links { "protobuf", "pthread" }
```

**Comment by dqzg12300** [comment]
可以了。就是这个问题。谢谢。
