### ISSUE TITLE
After build required lib, including lua and protobuf, but run the sln LuaPbIntf occured link error .

### ISSUE THREAD

**Issue by midGitub** [jinq0123/LuaPbIntf#2]
maybe there is something wrong with my procedure of building the lua lib.
![qq 20170512203735](https://cloud.githubusercontent.com/assets/20261416/25998338/12dddf30-3753-11e7-98fa-dc2ec82191b3.png)

Really appreciate your help
.

**Comment by midGitub** [comment]
B.t.w. Already place the build result lib to the custom folder.

**Comment by jinq0123** [comment]
By default, it expects the Lua library to build under C++.

See: https://github.com/jinq0123/LuaPbIntf/blob/master/third_party/README.md
