### ISSUE TITLE
在build过程中遇到麻烦

### ISSUE THREAD

**Issue by softwareyangsong** [jinq0123/LuaPbIntf#3]
有2个问题：
1.build过程中报错：
![image](https://user-images.githubusercontent.com/4987605/27424489-c705be04-5767-11e7-85cb-b911247404fa.png)，需要的xxx.h文件都已经拷贝到对应的目录里了。不知道是不是环境问题，如果是环境问题，请告知改如何配置环境；
2.在thrid_party里的readme.md里有说要拷贝lib目录到该目录里，请问这个lib是从哪里来的呢？谢谢。

**Comment by jinq0123** [comment]
1. "已有主体"可能是更改了工程文件或者LuaIntf文件造成。不是环境问题。
2. 库文件需要自己编译。请编译依赖库并复制*.lib.

**Comment by jinq0123** [comment]
LuaPbIntf VS2015工程带依赖库
http://download.csdn.net/detail/jq0123/9852979

**Comment by softwareyangsong** [comment]
非常感谢指导，在本地已经跑通了。现在的问题是：

**Comment by softwareyangsong** [comment]
1.生成的pbluaintf.dll如何被编译到tolua.dll里？
2.tolua_runtime里的介绍，貌似只能将c文件编译到tolua.dll里，尚未看到将dll文件编译到tolua.dll里的demo；
如何在tolua里直接使用luapbintf.dll呢？
求指导。

**Comment by softwareyangsong** [comment]
关于将c文件编译到tolua.dll里，我主要参考了这个：http://www.qingpingshan.com/rjbc/ios/239224.html，但不知道如何将dll编译到另一个dll里。

**Comment by jinq0123** [comment]
帮不了你。
