### ISSUE TITLE
can you help me  build error

### ISSUE THREAD

**Issue by lingfan** [jinq0123/LuaPbIntf#4]
1>------ 已启动生成: 项目: LuaPbIntf, 配置: Debug Win32 ------
1>    正在创建库 bin\Debug\luapbintf.lib 和对象 bin\Debug\luapbintf.exp
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_settop(struct lua_State *,int)" (?lua_settop@@YAXPAUlua_State@@H@Z)，该符号在函数 "public: void __thiscall LuaIntf::LuaRef::rawset<char const *,class LuaIntf::LuaRef>(char const * const &,class LuaIntf::LuaRef const &)" (??$rawset@PBDVLuaRef@LuaIntf@@@LuaRef@LuaIntf@@QAEXABQBDABV01@@Z) 中被引用
1>LuaPbIntfImpl.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_settop(struct lua_State *,int)" (?lua_settop@@YAXPAUlua_State@@H@Z)
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_settop(struct lua_State *,int)" (?lua_settop@@YAXPAUlua_State@@H@Z)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_settop(struct lua_State *,int)" (?lua_settop@@YAXPAUlua_State@@H@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_pushvalue(struct lua_State *,int)" (?lua_pushvalue@@YAXPAUlua_State@@H@Z)，该符号在函数 "public: __thiscall LuaIntf::LuaRef::LuaRef(struct lua_State *,int)" (??0LuaRef@LuaIntf@@QAE@PAUlua_State@@H@Z) 中被引用
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_pushvalue(struct lua_State *,int)" (?lua_pushvalue@@YAXPAUlua_State@@H@Z)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_pushvalue(struct lua_State *,int)" (?lua_pushvalue@@YAXPAUlua_State@@H@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_isuserdata(struct lua_State *,int)" (?lua_isuserdata@@YAHPAUlua_State@@H@Z)，该符号在函数 "public: static int __cdecl LuaIntf::CppBindMethodBase<0,void (__cdecl*)(void),1,void>::call(struct lua_State *)" (?call@?$CppBindMethodBase@$0A@P6AXXZ$00X$$V@LuaIntf@@SAHPAUlua_State@@@Z) 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_type(struct lua_State *,int)" (?lua_type@@YAHPAUlua_State@@H@Z)，该符号在函数 "public: static class LuaIntf::LuaRef __cdecl LuaIntf::LuaTypeMapping<class LuaIntf::LuaRef,void>::get(struct lua_State *,int)" (?get@?$LuaTypeMapping@VLuaRef@LuaIntf@@X@LuaIntf@@SA?AVLuaRef@2@PAUlua_State@@H@Z) 中被引用
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "int __cdecl lua_type(struct lua_State *,int)" (?lua_type@@YAHPAUlua_State@@H@Z)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "int __cdecl lua_type(struct lua_State *,int)" (?lua_type@@YAHPAUlua_State@@H@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void * __cdecl lua_touserdata(struct lua_State *,int)" (?lua_touserdata@@YAPAXPAUlua_State@@H@Z)，该符号在函数 "private: static int __cdecl LuaIntf::LuaRef::destructUserData<class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> >(struct lua_State *)" (??$destructUserData@V?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@LuaRef@LuaIntf@@CAHPAUlua_State@@@Z) 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_pushnil(struct lua_State *)" (?lua_pushnil@@YAXPAUlua_State@@@Z)，该符号在函数 "public: static void __cdecl LuaIntf::LuaTypeMapping<class LuaIntf::LuaRef,void>::push(struct lua_State *,class LuaIntf::LuaRef const &)" (?push@?$LuaTypeMapping@VLuaRef@LuaIntf@@X@LuaIntf@@SAXPAUlua_State@@ABVLuaRef@2@@Z) 中被引用
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_pushnil(struct lua_State *)" (?lua_pushnil@@YAXPAUlua_State@@@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "char const * __cdecl lua_pushlstring(struct lua_State *,char const *,unsigned int)" (?lua_pushlstring@@YAPBDPAUlua_State@@PBDI@Z)，该符号在函数 "public: static void __cdecl LuaIntf::LuaTypeMapping<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,void>::push(struct lua_State *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?push@?$LuaTypeMapping@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@X@LuaIntf@@SAXPAUlua_State@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "char const * __cdecl lua_pushlstring(struct lua_State *,char const *,unsigned int)" (?lua_pushlstring@@YAPBDPAUlua_State@@PBDI@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "char const * __cdecl lua_pushstring(struct lua_State *,char const *)" (?lua_pushstring@@YAPBDPAUlua_State@@PBD@Z)，该符号在函数 "public: static void __cdecl LuaIntf::LuaTypeMapping<char const *,void>::push(struct lua_State *,char const *)" (?push@?$LuaTypeMapping@PBDX@LuaIntf@@SAXPAUlua_State@@PBD@Z) 中被引用
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "char const * __cdecl lua_pushstring(struct lua_State *,char const *)" (?lua_pushstring@@YAPBDPAUlua_State@@PBD@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_pushcclosure(struct lua_State *,int (__cdecl*)(struct lua_State *),int)" (?lua_pushcclosure@@YAXPAUlua_State@@P6AH0@ZH@Z)，该符号在函数 "public: static class LuaIntf::LuaRef __cdecl LuaIntf::LuaRef::createFunction<void (__cdecl*)(void)>(struct lua_State *,int (__cdecl*)(struct lua_State *),void (__cdecl*const &)(void))" (??$createFunction@P6AXXZ@LuaRef@LuaIntf@@SA?AV01@PAUlua_State@@P6AH0@ZABQ6AXXZ@Z) 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_rawgeti(struct lua_State *,int,__int64)" (?lua_rawgeti@@YAHPAUlua_State@@H_J@Z)，该符号在函数 "public: __thiscall LuaIntf::LuaRef::LuaRef(class LuaIntf::LuaRef const &)" (??0LuaRef@LuaIntf@@QAE@ABV01@@Z) 中被引用
1>LuaPbIntfImpl.obj : error LNK2001: 无法解析的外部符号 "int __cdecl lua_rawgeti(struct lua_State *,int,__int64)" (?lua_rawgeti@@YAHPAUlua_State@@H_J@Z)
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "int __cdecl lua_rawgeti(struct lua_State *,int,__int64)" (?lua_rawgeti@@YAHPAUlua_State@@H_J@Z)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "int __cdecl lua_rawgeti(struct lua_State *,int,__int64)" (?lua_rawgeti@@YAHPAUlua_State@@H_J@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_createtable(struct lua_State *,int,int)" (?lua_createtable@@YAXPAUlua_State@@HH@Z)，该符号在函数 "private: static void __cdecl LuaIntf::LuaRef::pushUserDataFrom<class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> >(struct lua_State *,class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> const &)" (??$pushUserDataFrom@V?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@LuaRef@LuaIntf@@CAXPAUlua_State@@ABV?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@Z) 中被引用
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_createtable(struct lua_State *,int,int)" (?lua_createtable@@YAXPAUlua_State@@HH@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void * __cdecl lua_newuserdata(struct lua_State *,unsigned int)" (?lua_newuserdata@@YAPAXPAUlua_State@@I@Z)，该符号在函数 "private: static void __cdecl LuaIntf::LuaRef::pushUserDataFrom<void (__cdecl*)(void)>(struct lua_State *,void (__cdecl*const &)(void))" (??$pushUserDataFrom@P6AXXZ@LuaRef@LuaIntf@@CAXPAUlua_State@@ABQ6AXXZ@Z) 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_setfield(struct lua_State *,int,char const *)" (?lua_setfield@@YAXPAUlua_State@@HPBD@Z)，该符号在函数 "private: static void __cdecl LuaIntf::LuaRef::pushUserDataFrom<class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> >(struct lua_State *,class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> const &)" (??$pushUserDataFrom@V?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@LuaRef@LuaIntf@@CAXPAUlua_State@@ABV?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@Z) 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_rawset(struct lua_State *,int)" (?lua_rawset@@YAXPAUlua_State@@H@Z)，该符号在函数 "public: void __thiscall LuaIntf::LuaRef::rawset<char const *,class LuaIntf::LuaRef>(char const * const &,class LuaIntf::LuaRef const &)" (??$rawset@PBDVLuaRef@LuaIntf@@@LuaRef@LuaIntf@@QAEXABQBDABV01@@Z) 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_setmetatable(struct lua_State *,int)" (?lua_setmetatable@@YAHPAUlua_State@@H@Z)，该符号在函数 "private: static void __cdecl LuaIntf::LuaRef::pushUserDataFrom<class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> >(struct lua_State *,class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> const &)" (??$pushUserDataFrom@V?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@LuaRef@LuaIntf@@CAXPAUlua_State@@ABV?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@Z) 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "char const * __cdecl luaL_checklstring(struct lua_State *,int,unsigned int *)" (?luaL_checklstring@@YAPBDPAUlua_State@@HPAI@Z)，该符号在函数 "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl LuaIntf::LuaTypeMapping<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,void>::get(struct lua_State *,int)" (?get@?$LuaTypeMapping@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@X@LuaIntf@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAUlua_State@@H@Z) 中被引用
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "char const * __cdecl luaL_checklstring(struct lua_State *,int,unsigned int *)" (?luaL_checklstring@@YAPBDPAUlua_State@@HPAI@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "int __cdecl luaL_error(struct lua_State *,char const *,...)" (?luaL_error@@YAHPAUlua_State@@PBDZZ)，该符号在函数 __catch$??$destructUserData@V?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@0@Z@std@@@LuaRef@LuaIntf@@CAHPAUlua_State@@@Z$0 中被引用
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "int __cdecl luaL_ref(struct lua_State *,int)" (?luaL_ref@@YAHPAUlua_State@@H@Z)，该符号在函数 "private: __thiscall LuaIntf::LuaRef::LuaRef(struct lua_State *)" (??0LuaRef@LuaIntf@@AAE@PAUlua_State@@@Z) 中被引用
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "int __cdecl luaL_ref(struct lua_State *,int)" (?luaL_ref@@YAHPAUlua_State@@H@Z)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "int __cdecl luaL_ref(struct lua_State *,int)" (?luaL_ref@@YAHPAUlua_State@@H@Z)
1>LuaPbIntf.obj : error LNK2019: 无法解析的外部符号 "void __cdecl luaL_unref(struct lua_State *,int,int)" (?luaL_unref@@YAXPAUlua_State@@HH@Z)，该符号在函数 "public: __thiscall LuaIntf::LuaRef::~LuaRef(void)" (??1LuaRef@LuaIntf@@QAE@XZ) 中被引用
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "void __cdecl luaL_unref(struct lua_State *,int,int)" (?luaL_unref@@YAXPAUlua_State@@HH@Z)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "void __cdecl luaL_unref(struct lua_State *,int,int)" (?luaL_unref@@YAXPAUlua_State@@HH@Z)
1>LuaPbIntfImpl.obj : error LNK2019: 无法解析的外部符号 "void __cdecl luaL_checktype(struct lua_State *,int,int)" (?luaL_checktype@@YAXPAUlua_State@@HH@Z)，该符号在函数 "public: class LuaIntf::LuaRef const & __thiscall LuaIntf::LuaRef::checkType(enum LuaIntf::LuaTypeID)const " (?checkType@LuaRef@LuaIntf@@QBEABV12@W4LuaTypeID@2@@Z) 中被引用
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "char const * __cdecl lua_typename(struct lua_State *,int)" (?lua_typename@@YAPBDPAUlua_State@@H@Z)，该符号在函数 "public: char const * __thiscall LuaIntf::LuaRef::typeName(void)const " (?typeName@LuaRef@LuaIntf@@QBEPBDXZ) 中被引用
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_toboolean(struct lua_State *,int)" (?lua_toboolean@@YAHPAUlua_State@@H@Z)，该符号在函数 "public: static bool __cdecl LuaIntf::LuaTypeMapping<bool,void>::get(struct lua_State *,int)" (?get@?$LuaTypeMapping@_NX@LuaIntf@@SA_NPAUlua_State@@H@Z) 中被引用
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_rawequal(struct lua_State *,int,int)" (?lua_rawequal@@YAHPAUlua_State@@HH@Z)，该符号在函数 "public: bool __thiscall LuaIntf::LuaTableIterator::operator==(class LuaIntf::LuaTableIterator const &)const " (??8LuaTableIterator@LuaIntf@@QBE_NABV01@@Z) 中被引用
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_pushinteger(struct lua_State *,__int64)" (?lua_pushinteger@@YAXPAUlua_State@@_J@Z)，该符号在函数 "public: static void __cdecl LuaIntf::LuaIntegerTypeMapping<int>::push(struct lua_State *,int)" (?push@?$LuaIntegerTypeMapping@H@LuaIntf@@SAXPAUlua_State@@H@Z) 中被引用
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "void __cdecl lua_pushinteger(struct lua_State *,__int64)" (?lua_pushinteger@@YAXPAUlua_State@@_J@Z)
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_gettable(struct lua_State *,int)" (?lua_gettable@@YAHPAUlua_State@@H@Z)，该符号在函数 "public: class LuaIntf::LuaRef __thiscall LuaIntf::LuaTableRef::value<class LuaIntf::LuaRef>(void)const " (??$value@VLuaRef@LuaIntf@@@LuaTableRef@LuaIntf@@QBE?AVLuaRef@1@XZ) 中被引用
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "int __cdecl lua_gettable(struct lua_State *,int)" (?lua_gettable@@YAHPAUlua_State@@H@Z)
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "int __cdecl lua_next(struct lua_State *,int)" (?lua_next@@YAHPAUlua_State@@H@Z)，该符号在函数 "private: void __thiscall LuaIntf::LuaTableIterator::next(void)" (?next@LuaTableIterator@LuaIntf@@AAEXXZ) 中被引用
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "double __cdecl luaL_checknumber(struct lua_State *,int)" (?luaL_checknumber@@YANPAUlua_State@@H@Z)，该符号在函数 "public: static float __cdecl LuaIntf::LuaNumberTypeMapping<float>::get(struct lua_State *,int)" (?get@?$LuaNumberTypeMapping@M@LuaIntf@@SAMPAUlua_State@@H@Z) 中被引用
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "__int64 __cdecl luaL_checkinteger(struct lua_State *,int)" (?luaL_checkinteger@@YA_JPAUlua_State@@H@Z)，该符号在函数 "public: static int __cdecl LuaIntf::LuaIntegerTypeMapping<int>::get(struct lua_State *,int)" (?get@?$LuaIntegerTypeMapping@H@LuaIntf@@SAHPAUlua_State@@H@Z) 中被引用
1>MessageSetter.obj : error LNK2019: 无法解析的外部符号 "__int64 __cdecl luaL_len(struct lua_State *,int)" (?luaL_len@@YA_JPAUlua_State@@H@Z)，该符号在函数 "public: int __thiscall LuaIntf::LuaRef::len(void)const " (?len@LuaRef@LuaIntf@@QBEHXZ) 中被引用
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "private: static enum google::protobuf::FieldDescriptor::CppType const * const google::protobuf::FieldDescriptor::kTypeToCppTypeMap" (?kTypeToCppTypeMap@FieldDescriptor@protobuf@google@@0QBW4CppType@123@B)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "private: static enum google::protobuf::FieldDescriptor::CppType const * const google::protobuf::FieldDescriptor::kTypeToCppTypeMap" (?kTypeToCppTypeMap@FieldDescriptor@protobuf@google@@0QBW4CppType@123@B)
1>MessageSetter.obj : error LNK2001: 无法解析的外部符号 "private: static char const * const * const google::protobuf::FieldDescriptor::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQBDB)
1>MsgToTbl.obj : error LNK2001: 无法解析的外部符号 "private: static char const * const * const google::protobuf::FieldDescriptor::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQBDB)
1>MsgToTbl.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_pushnumber(struct lua_State *,double)" (?lua_pushnumber@@YAXPAUlua_State@@N@Z)，该符号在函数 "public: static void __cdecl LuaIntf::LuaNumberTypeMapping<float>::push(struct lua_State *,float)" (?push@?$LuaNumberTypeMapping@M@LuaIntf@@SAXPAUlua_State@@M@Z) 中被引用
1>MsgToTbl.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_pushboolean(struct lua_State *,int)" (?lua_pushboolean@@YAXPAUlua_State@@H@Z)，该符号在函数 "public: static void __cdecl LuaIntf::LuaTypeMapping<bool,void>::push(struct lua_State *,bool)" (?push@?$LuaTypeMapping@_NX@LuaIntf@@SAXPAUlua_State@@_N@Z) 中被引用
1>MsgToTbl.obj : error LNK2019: 无法解析的外部符号 "void __cdecl lua_settable(struct lua_State *,int)" (?lua_settable@@YAXPAUlua_State@@H@Z)，该符号在函数 "public: class LuaIntf::LuaTableRef & __thiscall LuaIntf::LuaTableRef::operator=<class LuaIntf::LuaRef>(class LuaIntf::LuaRef const &)" (??$?4VLuaRef@LuaIntf@@@LuaTableRef@LuaIntf@@QAEAAV01@ABVLuaRef@1@@Z) 中被引用
1>bin\Debug\luapbintf.dll : fatal error LNK1120: 34 个无法解析的外部命令
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by jinq0123** [comment]
Duplicate issue #2.

By default, it expects the Lua library to build under C++.
See: https://github.com/jinq0123/LuaPbIntf/blob/master/third_party/README.md

**Comment by lingfan** [comment]
谢谢 已经OK了  正常解析
