### ISSUE TITLE
您好，在lua协程中调用时出错了

### ISSUE THREAD

**Issue by wondergong** [jinq0123/LuaPbIntf#6]
您好，这个代码编译好so动态库，普通测试可以，但是在lua的协程中调用时，encode和decode就不生效了，请问造成这个的原因有哪些呢，测试了好久不知道原因，希望能够解答一下。

**Comment by jinq0123** [comment]
This is because the lua-intf issue: https://github.com/SteveKChiu/lua-intf/issues/131

**Comment by wondergong** [comment]
好的谢谢，正在尝试用#131的方法解决这个问题
